name: Update README Date

on:
  push:
    paths:
      - 'README.md'

jobs:
  update-readme-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README date
        run: |
          today=$(date +"%Y-%m-%d")
          sed -i "s/updated on [0-9-]*/updated on $today/" README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Updated README date to $today"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
