name: Update README Date

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README date
        run: |
          sed -i "s/Last updated:.*/Last updated: $(date)/" README.md
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          if git commit -m "Updated README date to $(date)"; then
            echo "Changes committed."
          else
            echo "No changes to commit."
          fi

      - name: Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin main || echo "Push failed. Check branch protection rules or PAT permissions."
